# Generated by Django 2.0.7 on 2018-09-02 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.TextField(verbose_name='text of the action')),
                ('action_type', models.TextField()),
                ('action_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='title of bill')),
                ('introduction_date', models.DateField(null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('bill_number', models.IntegerField(null=True, verbose_name='bill number (relative to congressional session)')),
                ('congress', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=10, null=True, verbose_name='type of bill (S, HR, HRJRES, etc.)')),
                ('cbo_cost_estimate', models.URLField(null=True)),
                ('bill_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BillSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('action_description', models.TextField()),
                ('action_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_summaries', to='billserve.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50, null=True)),
                ('system_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoSponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_original_cosponsor', models.BooleanField()),
                ('co_sponsorship_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LegislativeBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LegislativeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LegislativeSubjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField(null=True)),
                ('activity_count', models.IntegerField(default=1)),
                ('bills', models.ManyToManyField(to='billserve.Bill')),
                ('legislative_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='billserve.LegislativeSubject')),
            ],
        ),
        migrations.CreateModel(
            name='LegislativeSubjectSupportSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_count', models.IntegerField(default=0)),
                ('blue_count', models.IntegerField(default=0)),
                ('white_count', models.IntegerField(default=0)),
                ('bills', models.ManyToManyField(to='billserve.Bill')),
                ('legislative_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_split', to='billserve.LegislativeSubject')),
            ],
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yea', models.BooleanField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('legislator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='billserve.Legislator')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('billserve.legislator',),
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('legislator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='billserve.Legislator')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('billserve.legislator',),
        ),
        migrations.AddField(
            model_name='vote',
            name='legislator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Legislator'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='legislator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Legislator'),
        ),
        migrations.AddField(
            model_name='legislator',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_billserve.legislator_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='legislativesubjectactivity',
            name='legislator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislative_subject_activities', to='billserve.Legislator'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.State'),
        ),
        migrations.AddField(
            model_name='cosponsorship',
            name='legislator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Legislator'),
        ),
        migrations.AddField(
            model_name='committee',
            name='chamber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billserve.LegislativeBody'),
        ),
        migrations.AddField(
            model_name='bill',
            name='co_sponsors',
            field=models.ManyToManyField(related_name='co_sponsored_bills', through='billserve.CoSponsorship', to='billserve.Legislator', verbose_name='co-sponsors of the given bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='committees',
            field=models.ManyToManyField(to='billserve.Committee'),
        ),
        migrations.AddField(
            model_name='bill',
            name='legislative_subjects',
            field=models.ManyToManyField(related_name='bills', to='billserve.LegislativeSubject'),
        ),
        migrations.AddField(
            model_name='bill',
            name='originating_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billserve.LegislativeBody'),
        ),
        migrations.AddField(
            model_name='bill',
            name='policy_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billserve.PolicyArea'),
        ),
        migrations.AddField(
            model_name='bill',
            name='related_bills',
            field=models.ManyToManyField(to='billserve.Bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsors',
            field=models.ManyToManyField(related_name='sponsored_bills', to='billserve.Legislator', verbose_name='sponsors of the given bill'),
        ),
        migrations.AddField(
            model_name='action',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill'),
        ),
        migrations.AddField(
            model_name='action',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billserve.Committee'),
        ),
        migrations.AddField(
            model_name='senator',
            name='committees',
            field=models.ManyToManyField(related_name='senators', to='billserve.Committee'),
        ),
        migrations.AddField(
            model_name='senator',
            name='legislative_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senators', to='billserve.LegislativeBody'),
        ),
        migrations.AddField(
            model_name='senator',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senators', to='billserve.Party'),
        ),
        migrations.AddField(
            model_name='senator',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senators', to='billserve.State'),
        ),
        migrations.AddField(
            model_name='representative',
            name='committees',
            field=models.ManyToManyField(related_name='representatives', to='billserve.Committee'),
        ),
        migrations.AddField(
            model_name='representative',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative', to='billserve.District'),
        ),
        migrations.AddField(
            model_name='representative',
            name='legislative_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='billserve.LegislativeBody'),
        ),
        migrations.AddField(
            model_name='representative',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='billserve.Party'),
        ),
        migrations.AddField(
            model_name='representative',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='billserve.State'),
        ),
    ]
