# Generated by Django 2.0.7 on 2018-07-17 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.TextField(verbose_name='text of the action')),
                ('action_type', models.TextField()),
                ('action_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='title of bill')),
                ('summary', models.TextField(null=True, verbose_name='summary of bill')),
                ('introduction_date', models.DateTimeField(null=True, verbose_name='date bill was created')),
                ('last_modified', models.DateTimeField(null=True)),
                ('bill_number', models.IntegerField(verbose_name='bill number (relative to congressional session)')),
                ('type', models.CharField(max_length=10, null=True, verbose_name='type of bill (S, HR, HRJRES, etc.)')),
                ('cbo_cost_estimate', models.URLField(null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BillStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField()),
                ('url', models.URLField()),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill', verbose_name='related bill for bill status')),
            ],
        ),
        migrations.CreateModel(
            name='BillSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('originating_chamber', models.CharField(max_length=10)),
                ('original_publishing_date', models.DateField()),
                ('update_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_summaries', to='billserve.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoSponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_original_cosponsor', models.BooleanField()),
                ('co_sponsorship_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='LegislativeBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LegislativeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('committees', models.ManyToManyField(to='billserve.Committee')),
                ('legislative_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='billserve.LegislativeBody', verbose_name="legislator's legislative body")),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Legislator')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yea', models.BooleanField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Legislator')),
            ],
        ),
        migrations.AddField(
            model_name='legislator',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billserve.Party', verbose_name="legislator's party"),
        ),
        migrations.AddField(
            model_name='legislator',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billserve.State'),
        ),
        migrations.AddField(
            model_name='cosponsorship',
            name='legislator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Legislator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='co_sponsors',
            field=models.ManyToManyField(related_name='co_sponsored_bills', through='billserve.CoSponsorship', to='billserve.Legislator', verbose_name='co-sponsors of the given bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='legislative_subjects',
            field=models.ManyToManyField(to='billserve.LegislativeSubject'),
        ),
        migrations.AddField(
            model_name='bill',
            name='originating_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billserve.LegislativeBody'),
        ),
        migrations.AddField(
            model_name='bill',
            name='policy_areas',
            field=models.ManyToManyField(to='billserve.PolicyArea'),
        ),
        migrations.AddField(
            model_name='bill',
            name='related_bills',
            field=models.ManyToManyField(to='billserve.Bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsors',
            field=models.ManyToManyField(related_name='sponsored_bills', through='billserve.Sponsorship', to='billserve.Legislator', verbose_name='sponsors of the given bill'),
        ),
        migrations.AddField(
            model_name='action',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.Bill'),
        ),
        migrations.AddField(
            model_name='action',
            name='committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billserve.Committee'),
        ),
    ]
