# Generated by Django 2.0.7 on 2018-07-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.IntegerField(null=True, verbose_name='bill number (relative to congressional session)'),
        ),
    ]
