# Generated by Django 2.0.7 on 2018-07-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billserve', '0002_auto_20180716_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billserve.State')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('legislator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='billserve.Legislator')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billserve.District')),
            ],
            bases=('billserve.legislator',),
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('legislator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='billserve.Legislator')),
            ],
            bases=('billserve.legislator',),
        ),
    ]
